import Employee from "../models/Employee";
import ProjectTags from "../models/ProjectTags";
import InterestTags from "../models/InterestTags";
import UserProfile from "../models/UserProfile";

export const BASE_URL = "http://localhost:8080/api/employee";

export const FILTER_FIELDS = ["Name", "ID", "Pod", "Interest", "Project", "Department"];
export const DEFUALT_INITIALISE_EMPLOYEE: Employee = {
    name: "",
    employeeId: 0,
    designation: "",
    level: "0",
    slackURL: "",
    managerId: "0",
    email: "",
    contact: "",
    dob: new Date("0000-00-00"),
    address: "",
    department: "",
    date_of_joining: new Date("0000-00-00"),
    profileImageUrl: "",
    badgeImageUrl: "",
    pod: "",
    children: [],
};

export const DEFUALT_INITIALISE_USER_PROFILE: UserProfile = {
    employee: DEFUALT_INITIALISE_EMPLOYEE,
    interestTags: [],
    projectTags: [],
};

export const EMPLOYEE_DUMMY: Employee = {
    name: "Shrajan Pandey",
    employeeId: 2,
    designation: "SDE Intern",
    level: "0",
    slackURL: "",
    managerId: "0",
    email: "",
    contact: "",
    dob: new Date("0000-00-00"),
    address: "",
    department: "",
    date_of_joining: new Date("0000-00-00"),
    profileImageUrl: "/src/assets/IMG_20240127_171651_857.jpg",
    badgeImageUrl: "/src/assets/MoneyView.jpeg",
    children: [],
    pod: "growth",
};

export const PROJECT_TAGS_INITIALISE: ProjectTags = {
    projectId: "",
    projectManager: "",
    projectUrl: "",
    name: "",
};

export const INTEREST_TAGS_INITIALISE: InterestTags = {
    interestId: "",
    interestUrl: "",
    interestName: "",
};

export const PERSONAL_INFO = {
    name: "Name",
    employeeId: "Employee ID",
    department: "Department",
    designation: "Designation",
    pod: "Pod",
    level: "Level",
    managerId: "Manager",
    dob: "DOB",
    date_of_joining: "DOJ",
    address: "Address",
};

export enum DOCUMENTS {
    "Offer Letter",
    "Aadhar Card",
    "Pan Card",
    "Bank Detail",
}

export const DEMO_EMPLOYEES: Employee[] = [
    {
        name: "Shrajan Pandey",
        employeeId: 0,
        designation: "SDE Intern",
        level: "0",
        slackURL: "",
        managerId: "0",
        email: "",
        contact: "",
        dob: new Date("0000-00-00"),
        address: "",
        department: "",
        date_of_joining: new Date("0000-00-00"),
        profileImageUrl: "/src/assets/IMG_20240127_171651_857.jpg",
        badgeImageUrl: "/src/assets/MoneyView.jpeg",
        pod: "growth",
    },
    {
        name: "Shrajan Pandey",
        employeeId: 0,
        designation: "SDE Intern",
        level: "0",
        slackURL: "",
        managerId: "0",
        email: "",
        contact: "",
        dob: new Date("0000-00-00"),
        address: "",
        department: "",
        date_of_joining: new Date("0000-00-00"),
        profileImageUrl: "/src/assets/IMG_20240127_171651_857.jpg",
        badgeImageUrl: "/src/assets/MoneyView.jpeg",
        pod: "growth",
    },
    {
        name: "Shrajan Pandey",
        employeeId: 0,
        designation: "SDE Intern",
        level: "0",
        slackURL: "",
        managerId: "0",
        email: "",
        contact: "",
        dob: new Date("0000-00-00"),
        address: "",
        department: "",
        date_of_joining: new Date("0000-00-00"),
        profileImageUrl: "/src/assets/IMG_20240127_171651_857.jpg",
        badgeImageUrl: "/src/assets/MoneyView.jpeg",
        pod: "growth",
    },
    {
        name: "Shrajan Pandey",
        employeeId: 0,
        designation: "SDE Intern",
        level: "0",
        slackURL: "",
        managerId: "0",
        email: "",
        contact: "",
        dob: new Date("0000-00-00"),
        address: "",
        department: "",
        date_of_joining: new Date("0000-00-00"),
        profileImageUrl: "/src/assets/IMG_20240127_171651_857.jpg",
        badgeImageUrl: "/src/assets/MoneyView.jpeg",
        pod: "growth",
    },
    {
        name: "Shrajan Pandey",
        employeeId: 0,
        designation: "SDE Intern",
        level: "0",
        slackURL: "",
        managerId: "0",
        email: "",
        contact: "",
        dob: new Date("0000-00-00"),
        address: "",
        department: "",
        date_of_joining: new Date("0000-00-00"),
        profileImageUrl: "/src/assets/IMG_20240127_171651_857.jpg",
        badgeImageUrl: "/src/assets/MoneyView.jpeg",
        pod: "growth",
    },
    {
        name: "Shrajan Pandey",
        employeeId: 0,
        designation: "SDE Intern",
        level: "0",
        slackURL: "",
        managerId: "0",
        email: "",
        contact: "",
        dob: new Date("0000-00-00"),
        address: "",
        department: "",
        date_of_joining: new Date("0000-00-00"),
        profileImageUrl: "/src/assets/IMG_20240127_171651_857.jpg",
        badgeImageUrl: "/src/assets/MoneyView.jpeg",
        pod: "growth",
    },
    {
        name: "Shrajan Pandey",
        employeeId: 0,
        designation: "SDE Intern",
        level: "0",
        slackURL: "",
        managerId: "0",
        email: "",
        contact: "",
        dob: new Date("0000-00-00"),
        address: "",
        department: "",
        date_of_joining: new Date("0000-00-00"),
        profileImageUrl: "/src/assets/IMG_20240127_171651_857.jpg",
        badgeImageUrl: "/src/assets/MoneyView.jpeg",
        pod: "dev",
    },
    {
        name: "Shrajan Pandey",
        employeeId: 0,
        designation: "SDE Intern",
        level: "0",
        slackURL: "",
        managerId: "0",
        email: "",
        contact: "",
        dob: new Date("0000-00-00"),
        address: "",
        department: "",
        date_of_joining: new Date("0000-00-00"),
        profileImageUrl: "/src/assets/IMG_20240127_171651_857.jpg",
        badgeImageUrl: "/src/assets/MoneyView.jpeg",
        pod: "growth",
    },
    {
        name: "Shrajan Pandey",
        employeeId: 0,
        designation: "SDE Intern",
        level: "0",
        slackURL: "",
        managerId: "0",
        email: "",
        contact: "",
        dob: new Date("0000-00-00"),
        address: "",
        department: "",
        date_of_joining: new Date("0000-00-00"),
        profileImageUrl: "/src/assets/IMG_20240127_171651_857.jpg",
        badgeImageUrl: "/src/assets/MoneyView.jpeg",
        pod: "test",
    },
    {
        name: "Shrajan Pandey",
        employeeId: 0,
        designation: "SDE Intern",
        level: "0",
        slackURL: "",
        managerId: "0",
        email: "",
        contact: "",
        dob: new Date("0000-00-00"),
        address: "",
        department: "",
        date_of_joining: new Date("0000-00-00"),
        profileImageUrl: "/src/assets/IMG_20240127_171651_857.jpg",
        badgeImageUrl: "/src/assets/MoneyView.jpeg",
        pod: "test",
    },
    {
        name: "Shrajan Pandey",
        employeeId: 0,
        designation: "SDE Intern",
        level: "0",
        slackURL: "",
        managerId: "0",
        email: "",
        contact: "",
        dob: new Date("0000-00-00"),
        address: "",
        department: "",
        date_of_joining: new Date("0000-00-00"),
        profileImageUrl: "/src/assets/IMG_20240127_171651_857.jpg",
        badgeImageUrl: "/src/assets/MoneyView.jpeg",
        pod: "dev",
    },
];
